# Generated by Django 4.2.16 on 2024-11-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_variable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='systemvariable',
            table='system_variable',
        ),
    ]
