# Generated by Django 4.2.16 on 2024-11-10 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d+$', 'Phone number must contain only numbers.')])),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d+$', 'Phone number must contain only numbers.')])),
                ('bank_details', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[\\w\\s]+$', 'Bank details should not contain special characters.')])),
            ],
        ),
    ]
