# Generated by Django 4.2.16 on 2024-11-16 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_balance',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0, message='Balance cannot be negative.')]),
        ),
    ]
