services:
  db_service:
    image: mysql:latest
    container_name: dbservice
    env_file:
      - .env
    volumes:
      - gacha_db:/var/lib/mysql
      - ./MySql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $DATABASE_USER --password=$DATABASE_PASSWORD || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - app_network

  dbm_one:
    build: ./DbmOne
    container_name: dbmone
    volumes:
      - ./DbmOne:/app
    depends_on:
      db_service:
        condition: service_healthy
    networks:
      - app_network
    command: ["python", "manage.py", "test"]

  dbm_two:
    build: ./DbmTwo
    container_name: dbmtwo
    volumes:
      - ./DbmTwo:/app
    depends_on:
      db_service:
        condition: service_healthy
    networks:
      - app_network
    command: ["python", "manage.py", "test"]

  dbm_three:
    build: ./DbmThree
    container_name: dbmthree
    volumes:
      - ./DbmThree:/app
    depends_on:
      db_service:
        condition: service_healthy
    networks:
      - app_network
    command: ["python", "manage.py", "test"]

  auth_service:
    build: ./AuthService
    container_name: authservice
    volumes:
      - ./AuthService:/app
    depends_on:
      db_service:
        condition: service_healthy
      dbm_one:
        condition: service_started
    networks:
      - app_network

  user_service:
    build: ./UserService
    container_name: userservice
    volumes:
      - ./UserService:/app
    depends_on:
      db_service:
        condition: service_healthy
      dbm_two:
        condition: service_started
    networks:
      - app_network

  gacha_service:
    build: ./GachaService
    container_name: gachaservice
    volumes:
      - ./GachaService:/app
    depends_on:
      db_service:
        condition: service_healthy
      dbm_two:
        condition: service_started
      user_service:
        condition: service_started
    networks:
      - app_network

  play_service:
    build: ./PlayService
    container_name: playservice
    volumes:
      - ./PlayService:/app
    depends_on:
      db_service:
        condition: service_healthy
      gacha_service:
        condition: service_started
      dbm_three:
        condition: service_started
    networks:
      - app_network

  auction_service:
    build: ./AuctionService
    container_name: auctionservice
    volumes:
      - ./AuctionService:/app
    depends_on:
      db_service:
        condition: service_healthy
      dbm_three:
        condition: service_started
      play_service:
        condition: service_started
      gacha_service:
        condition: service_started
    networks:
      - app_network

  transaction_service:
    build: ./TransactionService
    container_name: transactionservice
    volumes:
      - ./TransactionService:/app
    depends_on:
      db_service:
        condition: service_healthy
      dbm_three:
        condition: service_started
      play_service:
        condition: service_started
      auction_service:
        condition: service_started
    networks:
      - app_network

  gateway_one:
    build: ./ApiGatewayOne
    container_name: gatewayone
    volumes:
      - ./ApiGatewayOne:/app
    depends_on:
      auth_service:
        condition: service_started
    ports:
      - 8001:8000
    networks:
      - app_network

  gateway_two:
    build: ./ApiGatewayTwo
    container_name: gatewaytwo
    volumes:
      - ./ApiGatewayTwo:/app
    depends_on:
      user_service:
        condition: service_started
      gacha_service:
        condition: service_started
    ports:
      - 8002:8000
    networks:
      - app_network

volumes:
  gacha_db:

networks:
  app_network:
    name: gachafinaldockered_app_network