name: Test Services with Docker Compose

on:
  push:
    branches:
      - "v1"
  pull_request:
    branches:
      - "v1"

jobs:
  test-services:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 4: Build the Docker Compose Services
    - name: Build Docker Compose Services
      run: |
        docker compose -f docker-compose.test.yml build --no-cache

    # Step 5: Run Docker Compose Services and Execute Tests
    - name: Run Tests in Docker Compose
      run: |
        docker compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from dbm_one

    # Step 6: Clean Up Resources
    - name: Clean Up Docker Compose
      if: always()
      run: docker compose -f docker-compose.test.yml down -v