# Generated by Django 4.2.16 on 2024-11-29 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGachaCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.BigIntegerField()),
                ('gacha_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'player_gacha_collection',
                'unique_together': {('player_id', 'gacha_id')},
            },
        ),
    ]
