openapi: 3.0.0
info:
  version: '1.0'
  title: ''
  description: ''
paths: {}
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/ABHUIYAN/Service/1.0