# Generated by Django 4.2.16 on 2024-11-17 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('banned', 'Banned'), ('Sold', 'sold')], default='inactive', max_length=8),
        ),
        migrations.CreateModel(
            name='AuctionGachas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_id', models.BigIntegerField()),
                ('collection_id', models.BigIntegerField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Price cannot be negative.')])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('banned', 'Banned'), ('Sold', 'sold')], default='active', max_length=10)),
            ],
            options={
                'db_table': 'auction_gachas',
                'unique_together': {('auction_id', 'collection_id')},
            },
        ),
    ]
