# Generated by Django 4.2.16 on 2024-11-17 20:12

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_auction_status_auctiongachas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionGachaBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_gacha_id', models.BigIntegerField()),
                ('bidder_id', models.BigIntegerField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Price must be a positive number.')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'auction_bids',
                'unique_together': {('auction_gacha_id', 'bidder_id', 'price')},
            },
        ),
    ]
