name: Docker Compose CI/CD

on:
  push:
    branches:
      - "v1"
  pull_request:
    branches:
      - "v1"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Build Docker Compose Services
    - name: Build Docker Compose Services
      run: |
        docker compose build --no-cache
    # Step 4: Start and Test Services
    - name: Run Docker Compose Services
      run: |
        docker compose up --abort-on-container-exit --exit-code-from gateway_one
    # Step 5: Clean Up
    - name: Clean Up Docker Compose
      if: always()
      run: docker compose down -v