# Generated by Django 4.2.16 on 2024-11-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gacha',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
