name: Docker Compose CI

on:
  push:
    branches:
      - "v1"
  pull_request:
    branches:
      - "v1"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Validate Docker Compose File
    - name: Validate Docker Compose Configuration
      run: docker compose -f docker-compose.test.yml config

    # Step 4: Build Docker Compose Services
    - name: Build Docker Compose Services
      run: docker compose -f docker-compose.test.yml build --no-cache

    # Step 5: Start Services
    - name: Start Docker Compose Services
      run: docker compose -f docker-compose.test.yml up -d

    # Step 6: Wait for Services
    - name: Wait for Services to Start
      run: sleep 30

    # Step 7: Validate Container Status
    - name: Validate Container Status
      run: docker compose ps -a

    # Step 8: Run Tests
    - name: Run Tests
      run: |
        docker compose exec dbm_one python manage.py test core --noinput
        docker compose exec dbm_two python manage.py test core --noinput

    # Step 9: Clean Up
    - name: Clean Up Docker Compose
      if: always()
      run: docker compose -f docker-compose.test.yml down -v